pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import qs.modules.common
import qs.modules.common.functions

/**
 * Manages Hyprland monitors: resolutions, refresh rates, scale, position,
 * transform, mirroring and VRR. Changes are applied live via Hyprland's Lua
 * evaluator and persisted as Lua loaded by quickshell/overrides.lua.
 */
Singleton {
    id: root

    // Raw list from `hyprctl monitors all -j` (includes disabled monitors and availableModes)
    property var list: []

    readonly property string persistPath: FileUtils.trimFileProtocol(`${Directories.config}/hypr/quickshell/monitors.lua`)
    readonly property string overridesPath: FileUtils.trimFileProtocol(`${Directories.config}/hypr/quickshell/overrides.lua`)
    readonly property string monitorsLoaderLine: "pcall(require, \"quickshell/monitors\")"

    function refresh() {
        getMonitors.running = true;
    }

    function luaString(value) {
        return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;
    }

    // Build a Hyprland Lua monitor call from a name and an options object.
    // opts: { disabled, mode ("WxH@Hz"|"preferred"|"highres"), position ("XxY"|"auto"),
    //         scale (number|"auto"), transform (int), mirror (name|"none"), vrr (bool) }
    function buildRule(name, opts) {
        if (opts.disabled)
            return `hl.monitor({ output = ${luaString(name)}, disabled = true })`;
        const mode = (opts.mode && `${opts.mode}`.length > 0) ? opts.mode : "preferred";
        const position = (opts.position && `${opts.position}`.length > 0) ? opts.position : "auto";
        const scale = (opts.scale === undefined || opts.scale === null || opts.scale === "") ? "auto" : opts.scale;
        const luaScale = typeof scale === "number" ? scale : luaString(scale);
        let fields = [`output = ${luaString(name)}`, `mode = ${luaString(mode)}`, `position = ${luaString(position)}`, `scale = ${luaScale}`];
        if (opts.transform !== undefined && opts.transform !== 0)
            fields.push(`transform = ${opts.transform}`);
        if (opts.mirror && opts.mirror !== "none" && `${opts.mirror}`.length > 0)
            fields.push(`mirror = ${luaString(opts.mirror)}`);
        if (opts.vrr !== undefined && opts.vrr !== null)
            fields.push(`vrr = ${opts.vrr ? 1 : 0}`);
        return `hl.monitor({ ${fields.join(", ")} })`;
    }

    // Apply a single monitor configuration live (does not persist).
    function apply(name, opts) {
        applyRule(buildRule(name, opts));
    }

    function applyRule(rule) {
        applyRules([rule]);
    }

    function applyRules(rules) {
        if (!rules || rules.length === 0)
            return;

        applyRulesProc.exec(["hyprctl", "eval", rules.join("\n")]);
    }

    // Persist already-built Lua calls to the file loaded by quickshell/overrides.lua.
    function persist(rules) {
        const header = "-- Generated by illogical-impulse Displays settings.\n" +
            "-- Hand edits may be overwritten by the settings app.\n";
        const body = rules.join("\n") + "\n";
        persistFileView.setText(header + body);

        const currentOverrides = overridesFileView.text();
        if (!currentOverrides.includes(root.monitorsLoaderLine)) {
            const separator = currentOverrides.length > 0 && !currentOverrides.endsWith("\n") ? "\n" : "";
            overridesFileView.setText(currentOverrides + separator + root.monitorsLoaderLine + "\n");
        }
    }

    FileView {
        id: persistFileView
        path: Qt.resolvedUrl(root.persistPath)
    }

    FileView {
        id: overridesFileView
        path: Qt.resolvedUrl(root.overridesPath)
    }

    Process {
        id: applyRulesProc

        stderr: StdioCollector {
            id: applyRulesError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0)
                console.warn("[Monitors] Failed to apply display configuration:", applyRulesError.text.trim());

            refreshDelay.restart();
        }
    }

    Timer {
        id: refreshDelay
        interval: 250
        onTriggered: root.refresh()
    }

    Component.onCompleted: refresh()

    Connections {
        target: Hyprland
        function onRawEvent(event) {
            if (["monitoradded", "monitoraddedv2", "monitorremoved", "monitorremovedv2"].includes(event.name))
                root.refresh();
        }
    }

    Process {
        id: getMonitors
        command: ["hyprctl", "monitors", "all", "-j"]
        stdout: StdioCollector {
            id: monitorsCollector
            onStreamFinished: {
                try {
                    root.list = JSON.parse(monitorsCollector.text);
                } catch (e) {
                    console.log("[Monitors] Failed to parse hyprctl output:", e);
                    root.list = [];
                }
            }
        }
    }
}
