pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import qs.modules.common
import qs.modules.common.functions

/**
 * Manages Hyprland monitors: resolutions, refresh rates, scale, position,
 * transform, mirroring and VRR. Changes are applied live via `hyprctl keyword
 * monitor` and can be persisted to a sourced Hyprland config file.
 */
Singleton {
    id: root

    // Raw list from `hyprctl monitors all -j` (includes disabled monitors and availableModes)
    property var list: []

    readonly property string persistPath: FileUtils.trimFileProtocol(`${Directories.config}/hypr/monitors.conf`)
    readonly property string persistSourceLine: "source = ~/.config/hypr/monitors.conf"

    function refresh() {
        getMonitors.running = true;
    }

    // Build a Hyprland monitor rule string from a name and an options object.
    // opts: { disabled, mode ("WxH@Hz"|"preferred"|"highres"), position ("XxY"|"auto"),
    //         scale (number|"auto"), transform (int), mirror (name|"none"), vrr (bool) }
    function buildRule(name, opts) {
        if (opts.disabled)
            return `${name}, disable`;
        const mode = (opts.mode && `${opts.mode}`.length > 0) ? opts.mode : "preferred";
        const position = (opts.position && `${opts.position}`.length > 0) ? opts.position : "auto";
        const scale = (opts.scale === undefined || opts.scale === null || opts.scale === "") ? "auto" : opts.scale;
        let rule = `${name}, ${mode}, ${position}, ${scale}`;
        if (opts.transform !== undefined && opts.transform !== 0)
            rule += `, transform, ${opts.transform}`;
        if (opts.mirror && opts.mirror !== "none" && `${opts.mirror}`.length > 0)
            rule += `, mirror, ${opts.mirror}`;
        if (opts.vrr !== undefined && opts.vrr !== null)
            rule += `, vrr, ${opts.vrr ? 1 : 0}`;
        return rule;
    }

    // Apply a single monitor configuration live (does not persist).
    function apply(name, opts) {
        applyRule(buildRule(name, opts));
    }

    function applyRule(rule) {
        Quickshell.execDetached(["hyprctl", "keyword", "monitor", rule]);
        refreshDelay.restart();
    }

    // Persist an array of already-built rule strings to a standalone config file.
    // This ONLY writes monitors.conf and never edits hyprland.conf — add
    // `source = ~/.config/hypr/monitors.conf` there yourself (once) to load it.
    function persist(rules) {
        const header = "# Generated by illogical-impulse Displays settings.\n" +
            "# Hand edits may be overwritten by the settings app.\n" +
            `# Load with: ${root.persistSourceLine}\n`;
        const body = rules.map(r => `monitor = ${r}`).join("\n") + "\n";
        const b64 = Qt.btoa(header + body);
        Quickshell.execDetached(["bash", "-c", `printf '%s' '${b64}' | base64 -d > '${root.persistPath}'`]);
    }

    Timer {
        id: refreshDelay
        interval: 250
        onTriggered: root.refresh()
    }

    Component.onCompleted: refresh()

    Connections {
        target: Hyprland
        function onRawEvent(event) {
            if (["monitoradded", "monitoraddedv2", "monitorremoved", "monitorremovedv2"].includes(event.name))
                root.refresh();
        }
    }

    Process {
        id: getMonitors
        command: ["hyprctl", "monitors", "all", "-j"]
        stdout: StdioCollector {
            id: monitorsCollector
            onStreamFinished: {
                try {
                    root.list = JSON.parse(monitorsCollector.text);
                } catch (e) {
                    console.log("[Monitors] Failed to parse hyprctl output:", e);
                    root.list = [];
                }
            }
        }
    }
}
